# Generated by Django 4.1.5 on 2023-06-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='continuous_cnt',
            field=models.IntegerField(null=True),
        ),
    ]
