# Generated by Django 4.1.5 on 2023-06-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_user_continuous_cnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='continuous_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
