name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: tsukiakarii/osod
          stage: main
          yaml: |
            name: osod
            app: python@3.9
            options:
              env:
                - name: DJANGO_SECRET
                  value: ${{ secrets.DJANGO_SECRET }}
                - name: SECRET_KEY
                  value: ${{ secrets.SECRET_KEY }}
                - name: EMAIL_HOST_PASSWORD
                  value: ${{ secrets.EMAIL_HOST_PASSWORD }}
                - name: SOCIAL_AUTH_GOOGLE_CLIENT_ID
                  value: ${{ secrets.SOCIAL_AUTH_GOOGLE_CLIENT_ID }}
                - name: SOCIAL_AUTH_GOOGLE_SECRET
                  value: ${{ secrets.SOCIAL_AUTH_GOOGLE_SECRET }}
                - name: DB_USER
                  value: ${{ secrets.DB_USER }}
                - name: DB_PASSWORD
                  value: ${{ secrets.DB_PASSWORD }}
                - name: DB_HOST
                  value: ${{ secrets.DB_HOST }}
                - name: DB_PORT
                  value: ${{ secrets.DB_PORT }}
                - name: OPEN_AI
                  value: ${{ secrets.OPEN_AI }}
              ports: 8000
              start: python manage.py runserver 0.0.0.0:8000 --noreload
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
              preset: python-django